"""Phase-4 Task 4: the DISCRIMINATING coupled-embedding gate -- reference + baseline layer.

The Phase-3 coupled claim was retracted twice because the fixed-far-field reference could not detect
a passive "offline clock + deposition" scheme. This layer pins the EVOLVING-far-field references
(fixtures, generated by scratch/m4_phase4_ref{A,B}_disperse.py / _refAB_drain.py) and PRE-REGISTERS
the discrimination battery: every documented PASSIVE baseline must FAIL at least one gate leg by
>= BASELINE_KILL, while the embedded scheme under test (Task 6/7) must pass ALL legs at
<= EMBEDDED_TOL. These constants are LOCKED from the measured 2026-06-10 baseline numbers BEFORE any
embedded-scheme run (no post-hoc tuning -- the Phase-3 lesson).

THE KILL-MAP (all numbers measured 2026-06-10, this file asserts them):
                              disperse A (3/5 r_w)   disperse B    drain A (3/5/10 r_w)   drain B
  raw cyl/throttle clocks       28-224% FAIL          52% FAIL       29-94% FAIL          70% FAIL
  capacity-clamped variants     0.6-2.7% pass!        8.5% pass!     >=29% FAIL (clamp     >=34% FAIL
                                                                     cannot fix UNDER-pred)
  planar-desorption variant         --                  --           12-15% / 32-38% /     34% FAIL
                                                                     57-61% -> FAILS R5/R10
  10 r_w disperse CONTROL: the raw clock is RIGHT there (0.5-1.0%) -- an embedded scheme that
  over-corrects fails the control.
So: Ref A disperse alone is INSUFFICIENT (the clamp family passes it -- encoded below as a design
regression test); the ensemble (+ drain legs + Ref B + the n-sweep in the embedded harness) kills
every documented passive. Plan: docs/plans/2026-06-10-m4-phase4-coupled-embedding-plan.md (Task 4).
"""
import numpy as np
import pytest

from pids_forward.physics.sorptive_closure import (
    F_cylindrical, F_throttle, throttle_params, sorptive_clock, rel_l2)

# ---- PRE-REGISTERED GATE CONSTANTS (locked 2026-06-10, before any embedded-scheme run) ------------
EMBEDDED_TOL = 0.10     # the embedded scheme must pass EVERY leg at <= this rel-L2, across n
BASELINE_KILL = 0.20    # every passive baseline must fail >= 1 leg by >= this (worst measured: 0.289)

R_W = 0.05
DISP = "tests/data/m4_phase4_refA_disperse.npz"
DISP_B = "tests/data/m4_phase4_refB_disperse.npz"
DRAIN = "tests/data/m4_phase4_refAB_drain.npz"


@pytest.fixture(scope="module")
def refs():
    return np.load(DISP), np.load(DISP_B), np.load(DRAIN)


def _planar(z):
    return np.ones_like(np.asarray(z, dtype=float))


def _clock(t, S, dth, F):
    return sorptive_clock(t, S, dth, R_W, F)


# ---- fixture sanity -------------------------------------------------------------------------------
def test_fixtures_sane(refs):
    a, b, d = refs
    for npz, soils, rs in ((a, ("LOAM", "SAND", "SILT"), (3, 5, 10)),
                           (d, ("LOAM", "SAND"), (3, 5, 10))):
        for s in soils:
            dth = float(npz[f"{s}_dtheta"])
            for k in rs:
                t, I, imax = npz[f"{s}_R{k}_t"], npz[f"{s}_R{k}_I"], float(npz[f"{s}_R{k}_Imax"])
                assert np.all(np.diff(t) > 0) and np.all(np.diff(I) >= -1e-12 * imax)
                assert I[-1] <= imax * (1 + 1e-9)
                assert abs(imax - dth * ((k * R_W) ** 2 - R_W ** 2) / (2 * R_W)) < 1e-12
    for npz, key in ((b, "LOAM"), (d, "LOAM_B")):
        t, I = npz[f"{key}_t"] if npz is d else npz["LOAM_t"], npz[f"{key}_I"] if npz is d else npz["LOAM_I"]
        assert np.all(np.diff(t) > 0) and np.all(np.diff(I) >= -1e-14)


# ---- disperse legs --------------------------------------------------------------------------------
def test_disperse_raw_clock_fails_the_discriminators(refs):
    a, _, _ = refs
    for s in ("LOAM", "SAND", "SILT"):
        S, dth = float(a[f"{s}_S"]), float(a[f"{s}_dtheta"])
        for k in (3, 5):
            t, I = a[f"{s}_R{k}_t"], a[f"{s}_R{k}_I"]
            e = rel_l2(_clock(t, S, dth, F_cylindrical), I)
            assert e >= 0.25, f"{s} R{k}: raw clock relL2 {e:.1%} -- discrimination lost"


def test_disperse_clock_passes_the_10rw_control(refs):
    """The 10 r_w partial-depletion control: the raw clock IS right there (0.5-1.0% measured). An
    embedded scheme must ALSO be right there -- this leg catches over-correction."""
    a, _, _ = refs
    for s in ("LOAM", "SAND", "SILT"):
        S, dth = float(a[f"{s}_S"]), float(a[f"{s}_dtheta"])
        t, I = a[f"{s}_R10_t"], a[f"{s}_R10_I"]
        e = rel_l2(_clock(t, S, dth, F_cylindrical), I)
        assert e <= 0.05, f"{s} R10 control drifted: clock relL2 {e:.1%}"


def test_design_regression_clamped_clock_passes_refA_alone(refs):
    """DESIGN KNOWLEDGE, asserted so it is never forgotten: the capacity-clamped clock PASSES the
    disperse depleting-reservoir legs (0.6-2.7% measured) -- Ref A disperse alone CANNOT discriminate
    against capacity-aware passives. The kill comes from the drain legs (clamping cannot fix the
    throttle's UNDER-prediction) -- see test_clamp_family_is_killed_by_the_drain_legs."""
    a, _, _ = refs
    for s in ("LOAM", "SAND", "SILT"):
        S, dth = float(a[f"{s}_S"]), float(a[f"{s}_dtheta"])
        for k in (3, 5):
            t, I, imax = a[f"{s}_R{k}_t"], a[f"{s}_R{k}_I"], float(a[f"{s}_R{k}_Imax"])
            e = rel_l2(np.minimum(_clock(t, S, dth, F_cylindrical), imax), I)
            assert e <= 0.05, f"{s} R{k}: clamped clock now fails Ref A ({e:.1%})? -- re-derive the kill-map"


def test_deployment_legs_R40(refs):
    """The DEPLOYMENT-REGIME axis (LOAM R=40 r_w + Ref B-40; added 2026-06-10 after the regime
    course-correction): raw clock fails both (26.6% / 34.1% measured); the clamped clock's numbers
    are documented (4.3% / 9.8% -- killed by the drain legs as before)."""
    a, _, _ = refs
    S, dth = float(a["LOAM_S"]), float(a["LOAM_dtheta"])
    t, I, imax = a["LOAM_R40_t"], a["LOAM_R40_I"], float(a["LOAM_R40_Imax"])
    clk = _clock(t, S, dth, F_cylindrical)
    assert rel_l2(clk, I) >= 0.20
    assert rel_l2(np.minimum(clk, imax), I) <= 0.07
    b40 = np.load("tests/data/m4_phase4_refB40_disperse.npz")
    t, I = b40["LOAM_t"], b40["LOAM_I"]
    clk = _clock(t, S, dth, F_cylindrical)
    assert rel_l2(clk, I) >= 0.25
    assert rel_l2(np.minimum(clk, float(b40["LOAM_Imax"])), I) <= 0.12


def test_deployment_legs_R40_sand_silt():
    """The SOIL-GENERALITY deployment legs (SAND + SILT at R=40 r_w; follow-up #2a of the
    2026-06-12 list): the same full-depletion structure as the LOAM R40 leg, generated
    ADDITIVELY (scratch/m4_phase4_refA40_sand_silt.py -- the committed LOAM fixtures are never
    regenerated). Measured 2026-06-12: raw clock fails 39.4% (SAND; its 3.5-d first-guess window
    left the bend too late-window at clock 19.5% sub-bar, so the window was extended to 14 d --
    t90 mid-window, the retune rule's design target -- BEFORE the embedded scheme was scored on
    the final leg) and 214.5% (SILT, 470-d window); the clamped clock documents the known
    refA-alone evasion (0.7% / 4.1%; killed by the drain legs as ever); early windows match the
    signed-off Phase-1b infinite-domain fixture at 0.15% / 0.37%."""
    a40 = np.load("tests/data/m4_phase4_refA40_sand_silt.npz")
    for s, clamp_doc in (("SAND", 0.04), ("SILT", 0.07)):
        S, dth = float(a40[f"{s}_S"]), float(a40[f"{s}_dtheta"])
        t, I, imax = a40[f"{s}_R40_t"], a40[f"{s}_R40_I"], float(a40[f"{s}_R40_Imax"])
        assert np.all(np.diff(t) > 0) and np.all(np.diff(I) >= -1e-12 * imax)
        assert I[-1] <= imax * (1 + 1e-9)
        assert abs(imax - dth * ((40 * R_W) ** 2 - R_W ** 2) / (2 * R_W)) < 1e-12
        clk = _clock(t, S, dth, F_cylindrical)
        assert rel_l2(clk, I) >= 0.20, f"{s} R40: raw-clock discrimination lost"
        assert rel_l2(np.minimum(clk, imax), I) <= clamp_doc, \
            f"{s} R40: clamped-clock evasion shifted -- re-derive the kill-map"


def test_refB_kills_the_raw_clock_and_documents_the_clamp_gap(refs):
    a, b, _ = refs
    t, I = b["LOAM_t"], b["LOAM_I"]
    S, dth = float(b["LOAM_S"]), float(b["LOAM_dtheta"])
    imax = float(b["LOAM_Imax"])
    raw = rel_l2(_clock(t, S, dth, F_cylindrical), I)
    assert raw >= 0.40, f"Ref B raw-clock discrimination lost ({raw:.1%}; measured 52.4%)"
    clamped = rel_l2(np.minimum(_clock(t, S, dth, F_cylindrical), imax), I)
    assert clamped <= EMBEDDED_TOL + 0.02, \
        f"clamped clock vs Ref B now {clamped:.1%} (measured 8.5%) -- kill-map shifted, re-derive"


# ---- drain legs (the clamp-family killer) ---------------------------------------------------------
def test_drain_raw_throttle_fails_refA(refs):
    _, _, d = refs
    for s in ("LOAM", "SAND"):
        S, dth = float(d[f"{s}_Sdes"]), float(d[f"{s}_dtheta"])
        z0, kk = throttle_params(dth)
        for k in (3, 5, 10):
            t, I = d[f"{s}_R{k}_t"], d[f"{s}_R{k}_I"]
            e = rel_l2(_clock(t, S, dth, lambda z: F_throttle(z, z0, kk)), I)
            assert e >= 0.25, f"{s} drain R{k}: throttle clock relL2 {e:.1%} -- discrimination lost"


def test_clamp_family_is_killed_by_the_drain_legs(refs):
    """Each passive drain variant (throttle / planar F=1 / cylindrical F, clamped or not) must fail
    at least one drain leg by >= BASELINE_KILL. Measured worst cases: throttle 28.9% (LOAM R3);
    planar 31.7% (LOAM R5); cyl 40.9% (LOAM R3). Clamping is a no-op or worse for under-prediction."""
    _, _, d = refs
    for s in ("LOAM", "SAND"):
        S, dth = float(d[f"{s}_Sdes"]), float(d[f"{s}_dtheta"])
        z0, kk = throttle_params(dth)
        for Fname, F in (("throttle", lambda z: F_throttle(z, z0, kk)),
                         ("planar", _planar), ("cyl", F_cylindrical)):
            worst = 0.0
            for k in (3, 5, 10):
                t, I, imax = d[f"{s}_R{k}_t"], d[f"{s}_R{k}_I"], float(d[f"{s}_R{k}_Imax"])
                clk = _clock(t, S, dth, F)
                worst = max(worst, min(rel_l2(clk, I), rel_l2(np.minimum(clk, imax), I)))
            assert worst >= BASELINE_KILL, \
                f"{s} drain variant '{Fname}': best-leg-evading relL2 {worst:.1%} < kill margin"


def test_drain_refB_kills_the_passives(refs):
    _, _, d = refs
    t, I = d["LOAM_B_t"], d["LOAM_B_I"]
    S, dth = float(d["LOAM_Sdes"]), float(d["LOAM_dtheta"])
    z0, kk = throttle_params(dth)
    imax = float(d["LOAM_R5_Imax"])
    for Fname, F in (("throttle", lambda z: F_throttle(z, z0, kk)),
                     ("planar", _planar), ("cyl", F_cylindrical)):
        clk = _clock(t, S, dth, F)
        e = min(rel_l2(clk, I), rel_l2(np.minimum(clk, imax), I))
        assert e >= 0.30, f"drain Ref B: passive '{Fname}' evades ({e:.1%}; measured >=33.6%)"
